oe-selftest: devtool: run without poky
If DISTRO is set to poky, the ptest DISTRO_FEATURE is enable. However,
without meta-poky layer, ptest packages are not compiled and the tests
fail with:
   ERROR: Nothing RPROVIDES 'cmake-example-ptest'...

(From OE-Core rev: 7129a974e882673b575dc2ca043f82f90577bb62)

Signed-off-by: Adrian Freihofer <adrian.freihofer@siemens.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>